2026-02-24

# 学習内容
### 書籍/教材:スッキリわかるPythonによる機械学習入門
### 範囲: 第12章 
### 目的: ロジスティクス回帰とランダムフォレストを理解する。

 -----------------------------
## <関数まとめ>



 -----------------------------
## <内容まとめ>

・**ロジスティック回帰**  
分類するための回帰式を作って、分類の予測モデルを作る手法である。  
ロジスティック回帰では、教師あり学習の正解データに対して、それぞれの確率を計算して、その多寡によって最終的な分類を判断する。基本的には**確率が一番大きい結果**を優先し、分類の結果判定に用いる。  
回帰式は正解データの種類の数だけ作られる。  

・**ロジスティック回帰の実装**  
```python
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(random_state = 0, C = 0.1, multi_class = 'auto', solver = 'lbfgs')
```
ここで引数Cは正規化項の重み定数の逆数である。リッジ回帰やラッソ回帰のalphaとは逆で、Cは小さいほうが、回帰式の係数を小さくしようとする働きが強くなり、過学習は防げる可能性があがる。  

・**正解データの確率を予測する**  
```python
モデル変数.predict_proba(二次元データ)
# 二次元データにはリストやデータフレームが指定できる。
```

・**ランダムフォレスト**  
ランダムフォレストは決定木の上位互換だと思っていいらしい。  
**ランダムフォレスト**は、たくさんの決定木を作成し、それぞれの木に予測させ、その結果の多数決で最終結果を求めるという手法。  
ランダムフォレストのように、さまざまな予測モデルを作成して、最終的に1つの予測結果を出す手法のことを**アンサンブル学習**という。  
ランダムフォレストでは、各決定木で利用するデータは行も列もランダムに選ぶようにして、作成する木に多様性を持たせて、多数決を行う。  
ランダムフォレストは「決定木でのバギング(後述)」を少し拡張した(列もランダム選択)手法と考えることができる。  

・**ランダムフォレストの実装**  
```python
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 100, random_state = 0, max_depth = 3)
# n_estimatorsで作成する決定木の数を指定
```

・**バギング**  
アンサンブル学習は**バギング**と**ブースティング**に分けることができる。 
バギングとは、訓練データを**ブートストラップサンプリング**することで、訓練データのデータセットをいくつか作り、それぞれモデルに学習させるもの。ブートストラップサンプリングとは、全データ(n個)の中から**復元抽出**により、n個のデータをランダムに抽出すること。復元抽出とは、2個以上のデータをランダムにサンプリングする際に、過去に選択したデータも選択対象に含めるサンプリング方法。  
ブートストラップサンプリングを表データに行う場合、全部でN行のデータに対して、復元抽出でN行分ランダムに選択する。1セットの表データから、様々なパターンの表データを作成することができる。作った表の数のぶんだけモデルを作成して、それぞれに学習させる。  

・**ブースティング**  
ブースティングでは、**モデルを1つずつ順番に学習させていく。** 
ブースティングでは、モデルは前のすでに学習が終わったモデルから、「ID○○番のデータを誤分類してしまった」や「学習した結果、MSE（平均2乗誤差）が△△」といった情報を受け取ることができる。モデルはこの受け取った情報を踏まえたうえで学習を進めるので、だんだんと精度が向上していく。  
ブースティングの手法にはXgboostや勾配ブースティングなどさまざまなものがある。それらの違いは、**次のモデルにどういう情報を渡すか**という点。  

・**アダブースト**  
ブースティングの手法の一つ。アダブーストでは、前回どのデータを誤分類してしまったのかという情報を渡す。各モデルは逐次的に予測性能も計算される。そして予測性能に応じて、重みを付与する。（データの受け渡しによってだんだんと予測性能があがっていく→重みが増えていく。）  

・**アダブーストの実装**  
```python
from sklearn.ensemble import AdaBoostClassifier

変数 = AdaBoostClassifier(n_estimators = モデル数, random_state = 数値, estimator = 決定木などのモデル)
```





 -----------------------------
## まとめ  

・ロジスティック回帰は分類の手法であり、正解データに分類される確率を予測する回帰式を作成する。  予測された確率が最大となるものを分類結果とする。  

・ランダムフォレストは利用するとデータと特徴量を毎回ランダムに選んでさまざまな決定木を作成する学習法。  

・ランダムフォレストの分類では、各分類木に予測をさせて、それらの多数決を行うことで、最終的な予測結論を下す。  

・ランダムフォレストは通常の決定木に比べ、過学習を防ぐことができる。  

・アダブーストは、大量のモデルを生成し、１つずつ逐次的に学習を進める。  

・アダブーストの各モデルは、前のモデルと学習結果を共有して学習を行う。学習後の予測は、各モデルの予測性能に応じて、重み付き多数決を行う。  



--------------------------------------
## 以下は実装例

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv('chap12/iris.csv')
df.head()

   がく片長さ  がく片幅  花弁長さ   花弁幅           種類
0   0.22  0.63  0.08  0.04  Iris-setosa
1   0.17  0.42  0.35  0.04  Iris-setosa
2   0.11  0.50  0.13  0.04  Iris-setosa
3   0.08  0.46  0.26  0.04  Iris-setosa
4   0.19  0.67  0.44  0.04  Iris-setosa

In [9]:
# 平均値による欠損値の穴埋め
df_mean = df.mean(numeric_only=True)
train2 = df.fillna(df_mean)

x = train2.loc[:, :'花弁幅']
t = train2['種類']

# 特徴量の標準化
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
new = sc.fit_transform(x)

In [10]:
x_train, x_val, y_train, y_val = train_test_split(new, t, test_size = 0.2, random_state = 0)
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(random_state = 0, C = 0.1, multi_class = 'auto', solver = 'lbfgs')

In [11]:
model.fit(x_train, y_train)
print(model.score(x_train, y_train))
model.score(x_val, y_val)

0.8666666666666667

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

0.8333333333333334

In [12]:
model.coef_

array([[-0.53168668,  0.48573155, -0.52638431, -0.83213317],
       [ 0.09482289, -0.44707757, -0.00107471, -0.04407356],
       [ 0.4368638 , -0.03865398,  0.52745902,  0.87620673]])

上一行がvirginicaの式の係数  
真ん中一行がversicolorの式の係数  
下一行がsetosaの式の係数

In [13]:
x_new = [[1, 2, 3, 4]]

model.predict(x_new)

array(['Iris-virginica'], dtype=object)

In [14]:
model.predict_proba(x_new)

array([[4.02790964e-05, 3.02983301e-03, 9.96929888e-01]])

In [15]:
df = pd.read_csv('chap12/Survived.csv')
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [19]:
def fill_age(df, pclass, survived, value):
    joken1 = df['Pclass'] == pclass
    joken2 = df['Survived'] == survived
    joken3 = df['Age'].isnull()
    df.loc[(joken1) & (joken2) & (joken3), 'Age'] = value
    return df

In [20]:
print(df.pivot_table(index="Pclass",columns="Survived",values='Age'))

df = fill_age(df, 1, 0, 43)
df = fill_age(df, 1, 1, 35)
df = fill_age(df, 2, 0, 33)
df = fill_age(df, 2, 1, 25)
df = fill_age(df, 3, 0, 26)
df = fill_age(df, 3, 1, 20)

Survived          0          1
Pclass
1         43.695312  35.368197
2         33.544444  25.901566
3         26.555556  20.646118

In [22]:
col = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

x = df[col]
t = df['Survived']


dummy = pd.get_dummies(df['Sex'], drop_first = True, dtype = int)
x = pd.concat([x, dummy], axis = 1)
x.head(2)

   Pclass   Age  SibSp  Parch     Fare  male
0       3  22.0      1      0   7.2500     1
1       1  38.0      1      0  71.2833     0

In [24]:
from sklearn.ensemble import RandomForestClassifier
x_train, x_test, y_train, y_test = train_test_split(x, t, test_size = 0.2, random_state = 0)
model = RandomForestClassifier(n_estimators = 200, random_state = 0)

In [25]:
model.fit(x_train, y_train)
print(model.score(x_train, y_train))
print(model.score(x_test, y_test))

0.9859550561797753
0.8770949720670391

In [26]:
importance = model.feature_importances_ # 特徴量重要度
pd.Series(importance, index = x_train.columns)

Pclass    0.080805
Age       0.298318
SibSp     0.048996
Parch     0.034688
Fare      0.282337
male      0.254856
dtype: float64